### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by williamdes** [codemirror/codemirror5#6657]
I have no idea how our users trigger such a bug but it makes so much of a long time it is logged in error reports
```js
function getText(item) {
  return typeof item == "string" ? item : item.text;
}
```

Here is a stacktrace sent to our error reporting server:
<details><summary>stacktrace</summary>
<p>

```json
{
    "id": 16776148,
    "error_name": "TypeError",
    "error_message": "Cannot read property 'text' of undefined",
    "pma_version": "5.1.0",
    "php_version": "7.4",
    "browser": "CHROME 84",
    "user_os": "Mac",
    "server_software": "UNKNOWN",
    "stackhash": "f00e3748e3125af2fe49fefa2a5b36ae",
    "configuration_storage": "enabled",
    "script_name": "index.php",
    "steps": null,
    "stacktrace": [
        {
            "func": "getText",
            "line": "39",
            "column": "50",
            "context": [
                "    if (mode === \"sql\") mode = \"text/x-sql\";",
                "    return CodeMirror.resolveMode(mode).identifierQuote || \"`\";",
                "  }",
                "",
                "  function getText(item) {",
                "    return typeof item == \"string\" ? item : item.text;",
                "  }",
                "",
                "  function wrapTable(name, value) {",
                "    if (isArray(value)) value = {columns: value}",
                "    if (!value.text) value.text = name"
            ],
            "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
        },
        {
            "func": "match",
            "line": "75",
            "column": "15",
            "context": [
                "    return result;",
                "  }",
                "",
                "  function match(string, word) {",
                "    var len = string.length;",
                "    var sub = getText(word).substr(0, len);",
                "    return string.toUpperCase() === sub.toUpperCase();",
                "  }",
                "",
                "  function addMatches(result, search, wordlist, formatter) {",
                "    if (isArray(wordlist)) {"
            ],
            "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
        },
        {
            "func": "addMatches",
            "line": "90",
            "column": "13",
            "context": [
                "        var val = wordlist[word]",
                "        if (!val || val === true)",
                "          val = word",
                "        else",
                "          val = val.displayText ? {text: val.text, displayText: val.display//...",
                "        if (match(search, val)) result.push(formatter(val))",
                "      }",
                "    }",
                "  }",
                "",
                "  function cleanName(name) {"
            ],
            "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
        },
        {
            "func": "nameCompletion",
            "line": "149",
            "column": "5",
            "context": [
                "    addMatches(result, string, tables, function(w) {",
                "      return useIdentifierQuotes ? insertIdentifierQuotes(w) : w;",
                "    });",
                "",
                "    // Try to complete columns from defaultTable",
                "    addMatches(result, string, defaultTable, function(w) {",
                "      return useIdentifierQuotes ? insertIdentifierQuotes(w) : w;",
                "    });",
                "",
                "    // Try to complete columns",
                "    string = nameParts.pop();"
            ],
            "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
        },
        {
            "func": "?",
            "line": "276",
            "column": "15",
            "context": [
                "    } else {",
                "      start = end = cur.ch;",
                "      search = \"\";",
                "    }",
                "    if (search.charAt(0) == \".\" || search.charAt(0) == identifierQuote) {",
                "      start = nameCompletion(cur, token, result, editor);",
                "    } else {",
                "      var objectOrClass = function(w, className) {",
                "        if (typeof w === \"object\") {",
                "          w.className = className;",
                "        } else {"
            ],
            "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
        },
        {
            "func": "fetchHints",
            "line": "435",
            "column": "20",
            "context": [
                "",
                "  function fetchHints(hint, cm, options, callback) {",
                "    if (hint.async) {",
                "      hint(cm, callback, options)",
                "    } else {",
                "      var result = hint(cm, options)",
                "      if (result && result.then) result.then(callback)",
                "      else callback(result)",
                "    }",
                "  }",
                ""
            ],
            "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
        },
        {
            "func": "run",
            "line": "448",
            "column": "11",
            "context": [
                "    if (helpers.length) {",
                "      var resolved = function(cm, callback, options) {",
                "        var app = applicableHelpers(cm, helpers);",
                "        function run(i) {",
                "          if (i == app.length) return callback(null)",
                "          fetchHints(app[i], cm, options, function(result) {",
                "            if (result && result.list.length > 0) callback(result)",
                "            else run(i + 1)",
                "          })",
                "        }",
                "        run(0)"
            ],
            "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
        },
        {
            "func": "resolved",
            "line": "453",
            "column": "9",
            "context": [
                "          fetchHints(app[i], cm, options, function(result) {",
                "            if (result && result.list.length > 0) callback(result)",
                "            else run(i + 1)",
                "          })",
                "        }",
                "        run(0)",
                "      }",
                "      resolved.async = true",
                "      resolved.supportsSelection = true",
                "      return resolved",
                "    } else if (words = cm.getHelper(cm.getCursor(), \"hintWords\")) {"
            ],
            "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
        },
        {
            "func": "fetchHints",
            "line": "433",
            "column": "7",
            "context": [
                "    return result",
                "  }",
                "",
                "  function fetchHints(hint, cm, options, callback) {",
                "    if (hint.async) {",
                "      hint(cm, callback, options)",
                "    } else {",
                "      var result = hint(cm, options)",
                "      if (result && result.then) result.then(callback)",
                "      else callback(result)",
                "    }"
            ],
            "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
        },
        {
            "func": "Completion.update",
            "line": "135",
            "column": "7",
            "context": [
                "    },",
                "",
                "    update: function(first) {",
                "      if (this.tick == null) return",
                "      var self = this, myTick = ++this.tick",
                "      fetchHints(this.options.hint, this.cm, this.options, function(data) {",
                "        if (self.tick == myTick) self.finishUpdate(data, first)",
                "      })",
                "    },",
                "",
                "    finishUpdate: function(data, first) {"
            ],
            "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
        }
    ],
    "full_report": {
        "pma_version": "5.1.0",
        "browser_name": "CHROME",
        "browser_version": "84.0.4147.135",
        "user_os": "Mac",
        "server_software": "Apache",
        "user_agent_string": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36",
        "locale": "de",
        "configuration_storage": "enabled",
        "php_version": "7.4.16",
        "script_name": "index.php",
        "exception_type": "js",
        "exception": {
            "mode": "stack",
            "name": "TypeError",
            "message": "Cannot read property 'text' of undefined",
            "stack": [
                {
                    "func": "getText",
                    "line": "39",
                    "column": "50",
                    "context": [
                        "    if (mode === \"sql\") mode = \"text/x-sql\";",
                        "    return CodeMirror.resolveMode(mode).identifierQuote || \"`\";",
                        "  }",
                        "",
                        "  function getText(item) {",
                        "    return typeof item == \"string\" ? item : item.text;",
                        "  }",
                        "",
                        "  function wrapTable(name, value) {",
                        "    if (isArray(value)) value = {columns: value}",
                        "    if (!value.text) value.text = name"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
                },
                {
                    "func": "match",
                    "line": "75",
                    "column": "15",
                    "context": [
                        "    return result;",
                        "  }",
                        "",
                        "  function match(string, word) {",
                        "    var len = string.length;",
                        "    var sub = getText(word).substr(0, len);",
                        "    return string.toUpperCase() === sub.toUpperCase();",
                        "  }",
                        "",
                        "  function addMatches(result, search, wordlist, formatter) {",
                        "    if (isArray(wordlist)) {"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
                },
                {
                    "func": "addMatches",
                    "line": "90",
                    "column": "13",
                    "context": [
                        "        var val = wordlist[word]",
                        "        if (!val || val === true)",
                        "          val = word",
                        "        else",
                        "          val = val.displayText ? {text: val.text, displayText: val.display//...",
                        "        if (match(search, val)) result.push(formatter(val))",
                        "      }",
                        "    }",
                        "  }",
                        "",
                        "  function cleanName(name) {"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
                },
                {
                    "func": "nameCompletion",
                    "line": "149",
                    "column": "5",
                    "context": [
                        "    addMatches(result, string, tables, function(w) {",
                        "      return useIdentifierQuotes ? insertIdentifierQuotes(w) : w;",
                        "    });",
                        "",
                        "    // Try to complete columns from defaultTable",
                        "    addMatches(result, string, defaultTable, function(w) {",
                        "      return useIdentifierQuotes ? insertIdentifierQuotes(w) : w;",
                        "    });",
                        "",
                        "    // Try to complete columns",
                        "    string = nameParts.pop();"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
                },
                {
                    "func": "?",
                    "line": "276",
                    "column": "15",
                    "context": [
                        "    } else {",
                        "      start = end = cur.ch;",
                        "      search = \"\";",
                        "    }",
                        "    if (search.charAt(0) == \".\" || search.charAt(0) == identifierQuote) {",
                        "      start = nameCompletion(cur, token, result, editor);",
                        "    } else {",
                        "      var objectOrClass = function(w, className) {",
                        "        if (typeof w === \"object\") {",
                        "          w.className = className;",
                        "        } else {"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/sql-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/sql-hint.js"
                },
                {
                    "func": "fetchHints",
                    "line": "435",
                    "column": "20",
                    "context": [
                        "",
                        "  function fetchHints(hint, cm, options, callback) {",
                        "    if (hint.async) {",
                        "      hint(cm, callback, options)",
                        "    } else {",
                        "      var result = hint(cm, options)",
                        "      if (result && result.then) result.then(callback)",
                        "      else callback(result)",
                        "    }",
                        "  }",
                        ""
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
                },
                {
                    "func": "run",
                    "line": "448",
                    "column": "11",
                    "context": [
                        "    if (helpers.length) {",
                        "      var resolved = function(cm, callback, options) {",
                        "        var app = applicableHelpers(cm, helpers);",
                        "        function run(i) {",
                        "          if (i == app.length) return callback(null)",
                        "          fetchHints(app[i], cm, options, function(result) {",
                        "            if (result && result.list.length > 0) callback(result)",
                        "            else run(i + 1)",
                        "          })",
                        "        }",
                        "        run(0)"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
                },
                {
                    "func": "resolved",
                    "line": "453",
                    "column": "9",
                    "context": [
                        "          fetchHints(app[i], cm, options, function(result) {",
                        "            if (result && result.list.length > 0) callback(result)",
                        "            else run(i + 1)",
                        "          })",
                        "        }",
                        "        run(0)",
                        "      }",
                        "      resolved.async = true",
                        "      resolved.supportsSelection = true",
                        "      return resolved",
                        "    } else if (words = cm.getHelper(cm.getCursor(), \"hintWords\")) {"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
                },
                {
                    "func": "fetchHints",
                    "line": "433",
                    "column": "7",
                    "context": [
                        "    return result",
                        "  }",
                        "",
                        "  function fetchHints(hint, cm, options, callback) {",
                        "    if (hint.async) {",
                        "      hint(cm, callback, options)",
                        "    } else {",
                        "      var result = hint(cm, options)",
                        "      if (result && result.then) result.then(callback)",
                        "      else callback(result)",
                        "    }"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
                },
                {
                    "func": "Completion.update",
                    "line": "135",
                    "column": "7",
                    "context": [
                        "    },",
                        "",
                        "    update: function(first) {",
                        "      if (this.tick == null) return",
                        "      var self = this, myTick = ++this.tick",
                        "      fetchHints(this.options.hint, this.cm, this.options, function(data) {",
                        "        if (self.tick == myTick) self.finishUpdate(data, first)",
                        "      })",
                        "    },",
                        "",
                        "    finishUpdate: function(data, first) {"
                    ],
                    "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
                    "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
                }
            ],
            "uri": "index.php?route=%2Ftable%2Fsql"
        }
    },
    "report_id": 69376,
    "created": "2021-03-31T18:37:15+02:00",
    "modified": "2021-03-31T18:37:15+02:00",
    "exception_type": false,
    "locale": "de"
}
```

</p>
</details>

![Sélection_2021041500:10:19001](https://user-images.githubusercontent.com/7784660/114787100-7ee0c800-9d7f-11eb-9caf-4f148f042a33.jpg)

**Comment by williamdes** [comment]
There is no reports before phpMyAdmin 4.7.0
phpMyAdmin 4.6 versions had [CodeMirror 5.3.0](https://github.com/phpmyadmin/phpmyadmin/blob/QA_4_6/js/codemirror/addon/hint/show-hint.js)

And phpMyAdmin 5.7 versions had [CodeMirror 5.22.1](https://github.com/phpmyadmin/phpmyadmin/blob/QA_4_7/js/codemirror/addon/hint/show-hint.js)

`5.3.0` is maybe a mistake in the naming of the version in the commit but anyway, here is the diff between the two upgrades: https://github.com/phpmyadmin/phpmyadmin/commit/58a7e778118c55013635a12f47145fb7e36a156b

I am not saying this is related but maybe in some way, I let you investigate or let me know if you need more details :)

**Comment by marijnh** [comment]
Do you know what kind of schema data you're passing to the SQL completer? If there's an undefined in the wrong place in that data, that would cause an error like this. Specifically, this seems to be related to `defaultTable`.

**Comment by williamdes** [comment]
I did some research without much success, here is the data we load into `instance.options.hintOptions.tables`

```json
[
   {
      "text":"commune",
      "columns":[
         {
            "text":"line",
            "displayText":"line | int(11) unsigned",
            "columnName":"line",
            "columnHint":"int(11) unsigned"
         },
         {
            "text":"code_dpt",
            "displayText":"code_dpt | varchar(2)",
            "columnName":"code_dpt",
            "columnHint":"varchar(2)"
         },
         {
            "text":"code_dir",
            "displayText":"code_dir | tinyint(2)",
            "columnName":"code_dir",
            "columnHint":"tinyint(2)"
         },
         {
            "text":"code_comm",
            "displayText":"code_comm | varchar(4)",
            "columnName":"code_comm",
            "columnHint":"varchar(4)"
         },
         {
            "text":"cle_rivoli",
            "displayText":"cle_rivoli | tinytext",
            "columnName":"cle_rivoli",
            "columnHint":"tinytext"
         },
         {
            "text":"libelle_comm",
            "displayText":"libelle_comm | varchar(50)",
            "columnName":"libelle_comm",
            "columnHint":"varchar(50)"
         },
         {
            "text":"type_comm",
            "displayText":"type_comm | enum('N','R')",
            "columnName":"type_comm",
            "columnHint":"enum('N','R')"
         },
         {
            "text":"caract_rur",
            "displayText":"caract_rur | tinytext",
            "columnName":"caract_rur",
            "columnHint":"tinytext"
         },
         {
            "text":"caract_popul",
            "displayText":"caract_popul | tinytext",
            "columnName":"caract_popul",
            "columnHint":"tinytext"
         },
         {
            "text":"popul_reel",
            "displayText":"popul_reel | tinytext",
            "columnName":"popul_reel",
            "columnHint":"tinytext"
         },
         {
            "text":"popul_apart",
            "displayText":"popul_apart | tinytext",
            "columnName":"popul_apart",
            "columnHint":"tinytext"
         },
         {
            "text":"popul_fict",
            "displayText":"popul_fict | tinytext",
            "columnName":"popul_fict",
            "columnHint":"tinytext"
         },
         {
            "text":"caract_annul",
            "displayText":"caract_annul | tinytext",
            "columnName":"caract_annul",
            "columnHint":"tinytext"
         },
         {
            "text":"date_annul",
            "displayText":"date_annul | tinytext",
            "columnName":"date_annul",
            "columnHint":"tinytext"
         },
         {
            "text":"date_crea",
            "displayText":"date_crea | tinytext",
            "columnName":"date_crea",
            "columnHint":"tinytext"
         }
      ]
   },
   {
      "text":"direction",
      "columns":[
         {
            "text":"line",
            "displayText":"line | int(11) unsigned",
            "columnName":"line",
            "columnHint":"int(11) unsigned"
         },
         {
            "text":"code_dpt",
            "displayText":"code_dpt | varchar(2)",
            "columnName":"code_dpt",
            "columnHint":"varchar(2)"
         },
         {
            "text":"code_dir",
            "displayText":"code_dir | tinyint(2)",
            "columnName":"code_dir",
            "columnHint":"tinyint(2)"
         },
         {
            "text":"libelle_dir",
            "displayText":"libelle_dir | varchar(30)",
            "columnName":"libelle_dir",
            "columnHint":"varchar(30)"
         }
      ]
   },
   {
      "text":"final",
      "columns":[
         {
            "text":"line",
            "displayText":"line | int(11) unsigned",
            "columnName":"line",
            "columnHint":"int(11) unsigned"
         },
         {
            "text":"inconnu",
            "displayText":"inconnu | tinytext",
            "columnName":"inconnu",
            "columnHint":"tinytext"
         }
      ]
   },
   {
      "text":"initial",
      "columns":[
         {
            "text":"line",
            "displayText":"line | int(11) unsigned",
            "columnName":"line",
            "columnHint":"int(11) unsigned"
         },
         {
            "text":"lbl_prod",
            "displayText":"lbl_prod | tinytext",
            "columnName":"lbl_prod",
            "columnHint":"tinytext"
         },
         {
            "text":"date_situ",
            "displayText":"date_situ | tinytext",
            "columnName":"date_situ",
            "columnHint":"tinytext"
         },
         {
            "text":"date_prod",
            "displayText":"date_prod | tinytext",
            "columnName":"date_prod",
            "columnHint":"tinytext"
         }
      ]
   },
   {
      "text":"voie",
      "columns":[
         {
            "text":"line",
            "displayText":"line | null",
            "columnName":"line",
            "columnHint":null
         },
         {
            "text":"code_dpt",
            "displayText":"code_dpt | varchar(2)",
            "columnName":"code_dpt",
            "columnHint":"varchar(2)"
         },
         {
            "text":"code_dir",
            "displayText":"code_dir | tinyint(2)",
            "columnName":"code_dir",
            "columnHint":"tinyint(2)"
         },
         {
            "text":"code_comm",
            "displayText":"code_comm | varchar(4)",
            "columnName":"code_comm",
            "columnHint":"varchar(4)"
         },
         {
            "text":"ident_voie",
            "displayText":"ident_voie | char(4)",
            "columnName":"ident_voie",
            "columnHint":"char(4)"
         },
         {
            "text":"cle_rivoli",
            "displayText":"cle_rivoli | tinytext",
            "columnName":"cle_rivoli",
            "columnHint":"tinytext"
         },
         {
            "text":"code_nature",
            "displayText":"code_nature | tinytext",
            "columnName":"code_nature",
            "columnHint":"tinytext"
         },
         {
            "text":"libelle_voie",
            "displayText":"libelle_voie | tinytext",
            "columnName":"libelle_voie",
            "columnHint":"tinytext"
         },
         {
            "text":"type_comm",
            "displayText":"type_comm | enum('N','R')",
            "columnName":"type_comm",
            "columnHint":"enum('N','R')"
         },
         {
            "text":"caract_rur",
            "displayText":"caract_rur | tinytext",
            "columnName":"caract_rur",
            "columnHint":"tinytext"
         },
         {
            "text":"caract_voie",
            "displayText":"caract_voie | tinytext",
            "columnName":"caract_voie",
            "columnHint":"tinytext"
         },
         {
            "text":"caract_popul",
            "displayText":"caract_popul | tinytext",
            "columnName":"caract_popul",
            "columnHint":"tinytext"
         },
         {
            "text":"popul_apart",
            "displayText":"popul_apart | tinytext",
            "columnName":"popul_apart",
            "columnHint":"tinytext"
         },
         {
            "text":"popul_fict",
            "displayText":"popul_fict | tinytext",
            "columnName":"popul_fict",
            "columnHint":"tinytext"
         },
         {
            "text":"caract_annul",
            "displayText":"caract_annul | tinytext",
            "columnName":"caract_annul",
            "columnHint":"tinytext"
         },
         {
            "text":"date_annul",
            "displayText":"date_annul | tinytext",
            "columnName":"date_annul",
            "columnHint":"tinytext"
         },
         {
            "text":"date_crea",
            "displayText":"date_crea | tinytext",
            "columnName":"date_crea",
            "columnHint":"tinytext"
         },
         {
            "text":"code_majic",
            "displayText":"code_majic | tinytext",
            "columnName":"code_majic",
            "columnHint":"tinytext"
         },
         {
            "text":"type_voie",
            "displayText":"type_voie | tinytext",
            "columnName":"type_voie",
            "columnHint":"tinytext"
         },
         {
            "text":"caract_lieudit",
            "displayText":"caract_lieudit | enum('','0','1')",
            "columnName":"caract_lieudit",
            "columnHint":"enum('','0','1')"
         },
         {
            "text":"dernier_mot",
            "displayText":"dernier_mot | varchar(20)",
            "columnName":"dernier_mot",
            "columnHint":"varchar(20)"
         }
      ]
   }
]
```

**Comment by williamdes** [comment]
I am not sure if this should be closed or not @marijnh 
But I am sure the about section of https://github.com/codemirror/dev has a typo ;)

**Comment by marijnh** [comment]
What kind of typo?

**Comment by williamdes** [comment]
> Develpment repository for the CodeMirror editor project

Development

**Comment by williamdes** [comment]
Hi @marijnh 

This still exists, we have a lot of automated reports for it

```
TypeError: Cannot read properties of undefined (reading 'text')
  at Completion.update(js/vendor/codemirror/addon/hint/show-hint.js:135:7)
  at fetchHints(js/vendor/codemirror/addon/hint/show-hint.js:453:7)
  at resolved(js/vendor/codemirror/addon/hint/show-hint.js:473:9)
  at run(js/vendor/codemirror/addon/hint/show-hint.js:468:11)
  at fetchHints(js/vendor/codemirror/addon/hint/show-hint.js:455:20)
  at ? (js/vendor/codemirror/addon/hint/sql-hint.js:276:15)
  at nameCompletion(js/vendor/codemirror/addon/hint/sql-hint.js:149:5)
  at addMatches(js/vendor/codemirror/addon/hint/sql-hint.js:90:13)
  at match(js/vendor/codemirror/addon/hint/sql-hint.js:75:15)
  at getText(js/vendor/codemirror/addon/hint/sql-hint.js:39:50)
```
```
TypeError: Cannot read properties of undefined (reading 'text')
  at CodeMirror.showHint(js/vendor/codemirror/addon/hint/show-hint.js:48:16)
  at Completion.update(js/vendor/codemirror/addon/hint/show-hint.js:135:7)
  at fetchHints(js/vendor/codemirror/addon/hint/show-hint.js:453:7)
  at resolved(js/vendor/codemirror/addon/hint/show-hint.js:473:9)
  at run(js/vendor/codemirror/addon/hint/show-hint.js:468:11)
  at fetchHints(js/vendor/codemirror/addon/hint/show-hint.js:455:20)
  at ? (js/vendor/codemirror/addon/hint/sql-hint.js:286:5)
  at addMatches(js/vendor/codemirror/addon/hint/sql-hint.js:90:13)
  at match(js/vendor/codemirror/addon/hint/sql-hint.js:75:15)
  at getText(js/vendor/codemirror/addon/hint/sql-hint.js:39:50)
```

**Comment by williamdes** [comment]
It affects a lot of users on a very long time span, like for ever
![image](https://user-images.githubusercontent.com/7784660/199955631-38d8aca2-cf2d-4f46-a99a-4c16484ec5e5.png)

**Comment by williamdes** [comment]
Hi @marijnh 
Maybe I can sponsor your work for this issue ?

**Comment by marijnh** [comment]
If you can set up a small stand-alone script that reproduces this, it's probably very easy to debug and fix, but with the information I have so far I don't really know where to look. The line numbers in those errors don't look like they refer to the current version of show-hint.js.

**Comment by williamdes** [comment]
Let's close this until I see it again
